// Auto-extracted from the original creativeform form.html.
// Country and language option lists used by the new AI-structured form.
window.CF_COUNTRY_OPTIONS = Object.freeze([
    { value: 'WW - Worldwide', label: 'WW - Worldwide' },
    { value: 'EU - European Union', label: 'EU - European Union' },
    { value: 'AF - Afghanistan', label: 'AF - Afghanistan' },
    { value: 'AX - Åland Islands', label: 'AX - Åland Islands' },
    { value: 'AL - Albania', label: 'AL - Albania' },
    { value: 'DZ - Algeria', label: 'DZ - Algeria' },
    { value: 'AS - American Samoa', label: 'AS - American Samoa' },
    { value: 'AD - Andorra', label: 'AD - Andorra' },
    { value: 'AO - Angola', label: 'AO - Angola' },
    { value: 'AI - Anguilla', label: 'AI - Anguilla' },
    { value: 'AQ - Antarctica', label: 'AQ - Antarctica' },
    { value: 'AG - Antigua and Barbuda', label: 'AG - Antigua and Barbuda' },
    { value: 'AR - Argentina', label: 'AR - Argentina' },
    { value: 'AM - Armenia', label: 'AM - Armenia' },
    { value: 'AW - Aruba', label: 'AW - Aruba' },
    { value: 'AU - Australia', label: 'AU - Australia' },
    { value: 'AT - Austria', label: 'AT - Austria' },
    { value: 'AZ - Azerbaijan', label: 'AZ - Azerbaijan' },
    { value: 'BS - Bahamas', label: 'BS - Bahamas' },
    { value: 'BH - Bahrain', label: 'BH - Bahrain' },
    { value: 'BD - Bangladesh', label: 'BD - Bangladesh' },
    { value: 'BB - Barbados', label: 'BB - Barbados' },
    { value: 'BY - Belarus', label: 'BY - Belarus' },
    { value: 'BE - Belgium', label: 'BE - Belgium' },
    { value: 'BZ - Belize', label: 'BZ - Belize' },
    { value: 'BJ - Benin', label: 'BJ - Benin' },
    { value: 'BM - Bermuda', label: 'BM - Bermuda' },
    { value: 'BT - Bhutan', label: 'BT - Bhutan' },
    { value: 'BO - Bolivia', label: 'BO - Bolivia' },
    { value: 'BA - Bosnia and Herzegovina', label: 'BA - Bosnia and Herzegovina' },
    { value: 'BW - Botswana', label: 'BW - Botswana' },
    { value: 'BR - Brazil', label: 'BR - Brazil' },
    { value: 'IO - British Indian Ocean Territory', label: 'IO - British Indian Ocean Territory' },
    { value: 'VG - British Virgin Islands', label: 'VG - British Virgin Islands' },
    { value: 'BN - Brunei', label: 'BN - Brunei' },
    { value: 'BG - Bulgaria', label: 'BG - Bulgaria' },
    { value: 'BF - Burkina Faso', label: 'BF - Burkina Faso' },
    { value: 'BI - Burundi', label: 'BI - Burundi' },
    { value: 'KH - Cambodia', label: 'KH - Cambodia' },
    { value: 'CM - Cameroon', label: 'CM - Cameroon' },
    { value: 'CA - Canada', label: 'CA - Canada' },
    { value: 'CV - Cape Verde', label: 'CV - Cape Verde' },
    { value: 'BQ - Caribbean Netherlands', label: 'BQ - Caribbean Netherlands' },
    { value: 'KY - Cayman Islands', label: 'KY - Cayman Islands' },
    { value: 'CF - Central African Republic', label: 'CF - Central African Republic' },
    { value: 'TD - Chad', label: 'TD - Chad' },
    { value: 'CL - Chile', label: 'CL - Chile' },
    { value: 'CN - China', label: 'CN - China' },
    { value: 'CX - Christmas Island', label: 'CX - Christmas Island' },
    { value: 'CC - Cocos Islands', label: 'CC - Cocos Islands' },
    { value: 'CO - Colombia', label: 'CO - Colombia' },
    { value: 'KM - Comoros', label: 'KM - Comoros' },
    { value: 'CK - Cook Islands', label: 'CK - Cook Islands' },
    { value: 'CR - Costa Rica', label: 'CR - Costa Rica' },
    { value: 'HR - Croatia', label: 'HR - Croatia' },
    { value: 'CU - Cuba', label: 'CU - Cuba' },
    { value: 'CW - Curaçao', label: 'CW - Curaçao' },
    { value: 'CY - Cyprus', label: 'CY - Cyprus' },
    { value: 'CZ - Czech Republic', label: 'CZ - Czech Republic' },
    { value: 'DK - Denmark', label: 'DK - Denmark' },
    { value: 'DJ - Djibouti', label: 'DJ - Djibouti' },
    { value: 'DM - Dominica', label: 'DM - Dominica' },
    { value: 'DO - Dominican Republic', label: 'DO - Dominican Republic' },
    { value: 'CD - DR Congo', label: 'CD - DR Congo' },
    { value: 'EC - Ecuador', label: 'EC - Ecuador' },
    { value: 'EG - Egypt', label: 'EG - Egypt' },
    { value: 'SV - El Salvador', label: 'SV - El Salvador' },
    { value: 'GQ - Equatorial Guinea', label: 'GQ - Equatorial Guinea' },
    { value: 'ER - Eritrea', label: 'ER - Eritrea' },
    { value: 'EE - Estonia', label: 'EE - Estonia' },
    { value: 'ET - Ethiopia', label: 'ET - Ethiopia' },
    { value: 'FK - Falkland Islands', label: 'FK - Falkland Islands' },
    { value: 'FO - Faroe Islands', label: 'FO - Faroe Islands' },
    { value: 'FJ - Fiji', label: 'FJ - Fiji' },
    { value: 'FI - Finland', label: 'FI - Finland' },
    { value: 'FR - France', label: 'FR - France' },
    { value: 'GF - French Guiana', label: 'GF - French Guiana' },
    { value: 'PF - French Polynesia', label: 'PF - French Polynesia' },
    { value: 'GA - Gabon', label: 'GA - Gabon' },
    { value: 'GM - Gambia', label: 'GM - Gambia' },
    { value: 'GE - Georgia', label: 'GE - Georgia' },
    { value: 'DE - Germany', label: 'DE - Germany' },
    { value: 'GH - Ghana', label: 'GH - Ghana' },
    { value: 'GI - Gibraltar', label: 'GI - Gibraltar' },
    { value: 'GR - Greece', label: 'GR - Greece' },
    { value: 'GL - Greenland', label: 'GL - Greenland' },
    { value: 'GD - Grenada', label: 'GD - Grenada' },
    { value: 'GP - Guadeloupe', label: 'GP - Guadeloupe' },
    { value: 'GU - Guam', label: 'GU - Guam' },
    { value: 'GT - Guatemala', label: 'GT - Guatemala' },
    { value: 'GG - Guernsey', label: 'GG - Guernsey' },
    { value: 'GN - Guinea', label: 'GN - Guinea' },
    { value: 'GW - Guinea-Bissau', label: 'GW - Guinea-Bissau' },
    { value: 'GY - Guyana', label: 'GY - Guyana' },
    { value: 'HT - Haiti', label: 'HT - Haiti' },
    { value: 'HN - Honduras', label: 'HN - Honduras' },
    { value: 'HK - Hong Kong', label: 'HK - Hong Kong' },
    { value: 'HU - Hungary', label: 'HU - Hungary' },
    { value: 'IS - Iceland', label: 'IS - Iceland' },
    { value: 'IN - India', label: 'IN - India' },
    { value: 'ID - Indonesia', label: 'ID - Indonesia' },
    { value: 'IR - Iran', label: 'IR - Iran' },
    { value: 'IQ - Iraq', label: 'IQ - Iraq' },
    { value: 'IE - Ireland', label: 'IE - Ireland' },
    { value: 'IM - Isle of Man', label: 'IM - Isle of Man' },
    { value: 'IL - Israel', label: 'IL - Israel' },
    { value: 'IT - Italy', label: 'IT - Italy' },
    { value: 'CI - Ivory Coast', label: 'CI - Ivory Coast' },
    { value: 'JM - Jamaica', label: 'JM - Jamaica' },
    { value: 'JP - Japan', label: 'JP - Japan' },
    { value: 'JE - Jersey', label: 'JE - Jersey' },
    { value: 'JO - Jordan', label: 'JO - Jordan' },
    { value: 'KZ - Kazakhstan', label: 'KZ - Kazakhstan' },
    { value: 'KE - Kenya', label: 'KE - Kenya' },
    { value: 'KI - Kiribati', label: 'KI - Kiribati' },
    { value: 'XK - Kosovo', label: 'XK - Kosovo' },
    { value: 'KW - Kuwait', label: 'KW - Kuwait' },
    { value: 'KG - Kyrgyzstan', label: 'KG - Kyrgyzstan' },
    { value: 'LA - Laos', label: 'LA - Laos' },
    { value: 'LV - Latvia', label: 'LV - Latvia' },
    { value: 'LB - Lebanon', label: 'LB - Lebanon' },
    { value: 'LS - Lesotho', label: 'LS - Lesotho' },
    { value: 'LR - Liberia', label: 'LR - Liberia' },
    { value: 'LY - Libya', label: 'LY - Libya' },
    { value: 'LI - Liechtenstein', label: 'LI - Liechtenstein' },
    { value: 'LT - Lithuania', label: 'LT - Lithuania' },
    { value: 'LU - Luxembourg', label: 'LU - Luxembourg' },
    { value: 'MO - Macau', label: 'MO - Macau' },
    { value: 'MK - Macedonia', label: 'MK - Macedonia' },
    { value: 'MG - Madagascar', label: 'MG - Madagascar' },
    { value: 'MW - Malawi', label: 'MW - Malawi' },
    { value: 'MY - Malaysia', label: 'MY - Malaysia' },
    { value: 'MV - Maldives', label: 'MV - Maldives' },
    { value: 'ML - Mali', label: 'ML - Mali' },
    { value: 'MT - Malta', label: 'MT - Malta' },
    { value: 'MH - Marshall Islands', label: 'MH - Marshall Islands' },
    { value: 'MQ - Martinique', label: 'MQ - Martinique' },
    { value: 'MR - Mauritania', label: 'MR - Mauritania' },
    { value: 'MU - Mauritius', label: 'MU - Mauritius' },
    { value: 'YT - Mayotte', label: 'YT - Mayotte' },
    { value: 'MX - Mexico', label: 'MX - Mexico' },
    { value: 'FM - Micronesia', label: 'FM - Micronesia' },
    { value: 'MD - Moldova', label: 'MD - Moldova' },
    { value: 'MC - Monaco', label: 'MC - Monaco' },
    { value: 'MN - Mongolia', label: 'MN - Mongolia' },
    { value: 'ME - Montenegro', label: 'ME - Montenegro' },
    { value: 'MS - Montserrat', label: 'MS - Montserrat' },
    { value: 'MA - Morocco', label: 'MA - Morocco' },
    { value: 'MZ - Mozambique', label: 'MZ - Mozambique' },
    { value: 'MM - Myanmar', label: 'MM - Myanmar' },
    { value: 'NA - Namibia', label: 'NA - Namibia' },
    { value: 'NR - Nauru', label: 'NR - Nauru' },
    { value: 'NP - Nepal', label: 'NP - Nepal' },
    { value: 'NL - Netherlands', label: 'NL - Netherlands' },
    { value: 'AN - Netherlands Antilles', label: 'AN - Netherlands Antilles' },
    { value: 'NC - New Caledonia', label: 'NC - New Caledonia' },
    { value: 'NZ - New Zealand', label: 'NZ - New Zealand' },
    { value: 'NI - Nicaragua', label: 'NI - Nicaragua' },
    { value: 'NE - Niger', label: 'NE - Niger' },
    { value: 'NG - Nigeria', label: 'NG - Nigeria' },
    { value: 'NU - Niue', label: 'NU - Niue' },
    { value: 'KP - North Korea', label: 'KP - North Korea' },
    { value: 'MP - Northern Mariana Islands', label: 'MP - Northern Mariana Islands' },
    { value: 'NO - Norway', label: 'NO - Norway' },
    { value: 'OM - Oman', label: 'OM - Oman' },
    { value: 'PK - Pakistan', label: 'PK - Pakistan' },
    { value: 'PW - Palau', label: 'PW - Palau' },
    { value: 'PS - Palestine', label: 'PS - Palestine' },
    { value: 'PA - Panama', label: 'PA - Panama' },
    { value: 'PG - Papua New Guinea', label: 'PG - Papua New Guinea' },
    { value: 'PY - Paraguay', label: 'PY - Paraguay' },
    { value: 'PE - Peru', label: 'PE - Peru' },
    { value: 'PH - Philippines', label: 'PH - Philippines' },
    { value: 'PN - Pitcairn', label: 'PN - Pitcairn' },
    { value: 'PL - Poland', label: 'PL - Poland' },
    { value: 'PT - Portugal', label: 'PT - Portugal' },
    { value: 'PR - Puerto Rico', label: 'PR - Puerto Rico' },
    { value: 'QA - Qatar', label: 'QA - Qatar' },
    { value: 'KR - Republic of Korea', label: 'KR - Republic of Korea' },
    { value: 'CG - Republic of the Congo', label: 'CG - Republic of the Congo' },
    { value: 'RE - Réunion', label: 'RE - Réunion' },
    { value: 'RO - Romania', label: 'RO - Romania' },
    { value: 'RU - Russian Federation', label: 'RU - Russian Federation' },
    { value: 'RW - Rwanda', label: 'RW - Rwanda' },
    { value: 'BL - Saint Barthelemy', label: 'BL - Saint Barthelemy' },
    { value: 'SH - Saint Helena', label: 'SH - Saint Helena' },
    { value: 'KN - Saint Kitts and Nevis', label: 'KN - Saint Kitts and Nevis' },
    { value: 'LC - Saint Lucia', label: 'LC - Saint Lucia' },
    { value: 'MF - Saint Martin', label: 'MF - Saint Martin' },
    { value: 'PM - Saint Pierre and Miquelon', label: 'PM - Saint Pierre and Miquelon' },
    { value: 'VC - Saint Vincent and the Grenadines', label: 'VC - Saint Vincent and the Grenadines' },
    { value: 'WS - Samoa', label: 'WS - Samoa' },
    { value: 'SM - San Marino', label: 'SM - San Marino' },
    { value: 'ST - São Tomé & Príncipe', label: 'ST - São Tomé & Príncipe' },
    { value: 'SA - Saudi Arabia', label: 'SA - Saudi Arabia' },
    { value: 'SN - Senegal', label: 'SN - Senegal' },
    { value: 'RS - Serbia', label: 'RS - Serbia' },
    { value: 'SC - Seychelles', label: 'SC - Seychelles' },
    { value: 'SL - Sierra Leone', label: 'SL - Sierra Leone' },
    { value: 'SG - Singapore', label: 'SG - Singapore' },
    { value: 'SX - Sint Maarten', label: 'SX - Sint Maarten' },
    { value: 'SK - Slovakia', label: 'SK - Slovakia' },
    { value: 'SI - Slovenia', label: 'SI - Slovenia' },
    { value: 'SB - Solomon Islands', label: 'SB - Solomon Islands' },
    { value: 'SO - Somalia', label: 'SO - Somalia' },
    { value: 'ZA - South Africa', label: 'ZA - South Africa' },
    { value: 'SS - South Sudan', label: 'SS - South Sudan' },
    { value: 'ES - Spain', label: 'ES - Spain' },
    { value: 'LK - Sri Lanka', label: 'LK - Sri Lanka' },
    { value: 'SD - Sudan', label: 'SD - Sudan' },
    { value: 'SR - Suriname', label: 'SR - Suriname' },
    { value: 'SJ - Svalbard and Jan Mayen', label: 'SJ - Svalbard and Jan Mayen' },
    { value: 'SZ - Swaziland', label: 'SZ - Swaziland' },
    { value: 'SE - Sweden', label: 'SE - Sweden' },
    { value: 'CH - Switzerland', label: 'CH - Switzerland' },
    { value: 'SY - Syria', label: 'SY - Syria' },
    { value: 'TW - Taiwan (Province of China)', label: 'TW - Taiwan (Province of China)' },
    { value: 'TJ - Tajikistan', label: 'TJ - Tajikistan' },
    { value: 'TZ - Tanzania', label: 'TZ - Tanzania' },
    { value: 'TH - Thailand', label: 'TH - Thailand' },
    { value: 'TL - Timor-Leste', label: 'TL - Timor-Leste' },
    { value: 'TG - Togo', label: 'TG - Togo' },
    { value: 'TK - Tokelau', label: 'TK - Tokelau' },
    { value: 'TO - Tonga', label: 'TO - Tonga' },
    { value: 'TT - Trinidad and Tobago', label: 'TT - Trinidad and Tobago' },
    { value: 'TN - Tunisia', label: 'TN - Tunisia' },
    { value: 'TR - Turkey', label: 'TR - Turkey' },
    { value: 'TM - Turkmenistan', label: 'TM - Turkmenistan' },
    { value: 'TC - Turks and Caicos Islands', label: 'TC - Turks and Caicos Islands' },
    { value: 'TV - Tuvalu', label: 'TV - Tuvalu' },
    { value: 'UG - Uganda', label: 'UG - Uganda' },
    { value: 'UA - Ukraine', label: 'UA - Ukraine' },
    { value: 'AE - United Arab Emirates', label: 'AE - United Arab Emirates' },
    { value: 'GB - United Kingdom', label: 'GB - United Kingdom' },
    { value: 'US - United States', label: 'US - United States' },
    { value: 'VI - United States Virgin Islands', label: 'VI - United States Virgin Islands' },
    { value: 'UY - Uruguay', label: 'UY - Uruguay' },
    { value: 'UZ - Uzbekistan', label: 'UZ - Uzbekistan' },
    { value: 'VU - Vanuatu', label: 'VU - Vanuatu' },
    { value: 'VA - Vatican', label: 'VA - Vatican' },
    { value: 'VE - Venezuela', label: 'VE - Venezuela' },
    { value: 'VN - Vietnam', label: 'VN - Vietnam' },
    { value: 'WF - Wallis and Futuna', label: 'WF - Wallis and Futuna' },
    { value: 'EH - Western Sahara', label: 'EH - Western Sahara' },
    { value: 'YE - Yemen', label: 'YE - Yemen' },
    { value: 'ZM - Zambia', label: 'ZM - Zambia' },
    { value: 'ZW - Zimbabwe', label: 'ZW - Zimbabwe' },
]);

window.CF_LANG_OPTIONS = Object.freeze([
    { value: 'az - азербайджанский', label: 'az - азербайджанский' },
    { value: 'sq - албанский', label: 'sq - албанский' },
    { value: 'am - амхарский', label: 'am - амхарский' },
    { value: 'en - английский', label: 'en - английский' },
    { value: 'ar - арабский', label: 'ar - арабский' },
    { value: 'hy - армянский', label: 'hy - армянский' },
    { value: 'af - африкаанс', label: 'af - африкаанс' },
    { value: 'eu - баскский', label: 'eu - баскский' },
    { value: 'be - белорусский', label: 'be - белорусский' },
    { value: 'bn - бенгальский', label: 'bn - бенгальский' },
    { value: 'my - бирманский', label: 'my - бирманский' },
    { value: 'bg - болгарский', label: 'bg - болгарский' },
    { value: 'bs - боснийский', label: 'bs - боснийский' },
    { value: 'cy - валлийский', label: 'cy - валлийский' },
    { value: 'hu - венгерский', label: 'hu - венгерский' },
    { value: 'vi - вьетнамский', label: 'vi - вьетнамский' },
    { value: 'haw - гавайский', label: 'haw - гавайский' },
    { value: 'gl - галисийский', label: 'gl - галисийский' },
    { value: 'el - греческий', label: 'el - греческий' },
    { value: 'ka - грузинский', label: 'ka - грузинский' },
    { value: 'gu - гуджарати', label: 'gu - гуджарати' },
    { value: 'da - датский', label: 'da - датский' },
    { value: 'zu - зулу', label: 'zu - зулу' },
    { value: 'iw - иврит', label: 'iw - иврит' },
    { value: 'ig - игбо', label: 'ig - игбо' },
    { value: 'yi - идиш', label: 'yi - идиш' },
    { value: 'id - индонезийский', label: 'id - индонезийский' },
    { value: 'ga - ирландский', label: 'ga - ирландский' },
    { value: 'is - исландский', label: 'is - исландский' },
    { value: 'es - испанский', label: 'es - испанский' },
    { value: 'it - итальянский', label: 'it - итальянский' },
    { value: 'yo - йоруба', label: 'yo - йоруба' },
    { value: 'kk - казахский', label: 'kk - казахский' },
    { value: 'kn - каннада', label: 'kn - каннада' },
    { value: 'ca - каталанский', label: 'ca - каталанский' },
    { value: 'ky - киргизский', label: 'ky - киргизский' },
    { value: 'zh-TW - китайский (традиционный)', label: 'zh-TW - китайский (традиционный)' },
    { value: 'zh - китайский (упрощенный)', label: 'zh - китайский (упрощенный)' },
    { value: 'ko - корейский', label: 'ko - корейский' },
    { value: 'co - корсиканский', label: 'co - корсиканский' },
    { value: 'ht - креольский (Гаити)', label: 'ht - креольский (Гаити)' },
    { value: 'ku - курманджи', label: 'ku - курманджи' },
    { value: 'km - кхмерский', label: 'km - кхмерский' },
    { value: 'xh - кхоса', label: 'xh - кхоса' },
    { value: 'lo - лаосский', label: 'lo - лаосский' },
    { value: 'la - латинский', label: 'la - латинский' },
    { value: 'lv - латышский', label: 'lv - латышский' },
    { value: 'lt - литовский', label: 'lt - литовский' },
    { value: 'lb - люксембургский', label: 'lb - люксембургский' },
    { value: 'mk - македонский', label: 'mk - македонский' },
    { value: 'mg - малагасийский', label: 'mg - малагасийский' },
    { value: 'ms - малайский', label: 'ms - малайский' },
    { value: 'ml - малаялам', label: 'ml - малаялам' },
    { value: 'mt - мальтийский', label: 'mt - мальтийский' },
    { value: 'mi - маори', label: 'mi - маори' },
    { value: 'mr - маратхи', label: 'mr - маратхи' },
    { value: 'mn - монгольский', label: 'mn - монгольский' },
    { value: 'de - немецкий', label: 'de - немецкий' },
    { value: 'ne - непальский', label: 'ne - непальский' },
    { value: 'nl - нидерландский', label: 'nl - нидерландский' },
    { value: 'no - норвежский', label: 'no - норвежский' },
    { value: 'or - ория', label: 'or - ория' },
    { value: 'pa - панджаби', label: 'pa - панджаби' },
    { value: 'fa - персидский', label: 'fa - персидский' },
    { value: 'pl - польский', label: 'pl - польский' },
    { value: 'pt - португальский', label: 'pt - португальский' },
    { value: 'ps - пушту', label: 'ps - пушту' },
    { value: 'rw - руанда (киньяруанда)', label: 'rw - руанда (киньяруанда)' },
    { value: 'ro - румынский', label: 'ro - румынский' },
    { value: 'ru - русский', label: 'ru - русский' },
    { value: 'sm - самоанский', label: 'sm - самоанский' },
    { value: 'ceb - себуанский', label: 'ceb - себуанский' },
    { value: 'sr - сербский', label: 'sr - сербский' },
    { value: 'st - сесото', label: 'st - сесото' },
    { value: 'si - сингальский', label: 'si - сингальский' },
    { value: 'sd - синдхи', label: 'sd - синдхи' },
    { value: 'sk - словацкий', label: 'sk - словацкий' },
    { value: 'sl - словенский', label: 'sl - словенский' },
    { value: 'so - сомалийский', label: 'so - сомалийский' },
    { value: 'sw - суахили', label: 'sw - суахили' },
    { value: 'su - сунданский', label: 'su - сунданский' },
    { value: 'tg - таджикский', label: 'tg - таджикский' },
    { value: 'th - тайский', label: 'th - тайский' },
    { value: 'ta - тамильский', label: 'ta - тамильский' },
    { value: 'tt - татарский', label: 'tt - татарский' },
    { value: 'te - телугу', label: 'te - телугу' },
    { value: 'tr - турецкий', label: 'tr - турецкий' },
    { value: 'tk - туркменский', label: 'tk - туркменский' },
    { value: 'uz - узбекский', label: 'uz - узбекский' },
    { value: 'ug - уйгурский', label: 'ug - уйгурский' },
    { value: 'uk - украинский', label: 'uk - украинский' },
    { value: 'ur - урду', label: 'ur - урду' },
    { value: 'tl - филиппинский (тагальский)', label: 'tl - филиппинский (тагальский)' },
    { value: 'fi - финский', label: 'fi - финский' },
    { value: 'fr - французский', label: 'fr - французский' },
    { value: 'fy - фризский', label: 'fy - фризский' },
    { value: 'ha - хауса', label: 'ha - хауса' },
    { value: 'hi - хинди', label: 'hi - хинди' },
    { value: 'hmn - хмонг', label: 'hmn - хмонг' },
    { value: 'hr - хорватский', label: 'hr - хорватский' },
    { value: 'ny - чева (ньянджа)', label: 'ny - чева (ньянджа)' },
    { value: 'cs - чешский', label: 'cs - чешский' },
    { value: 'sv - шведский', label: 'sv - шведский' },
    { value: 'sn - шона', label: 'sn - шона' },
    { value: 'gd - шотландский (гэльский, кельтский)', label: 'gd - шотландский (гэльский, кельтский)' },
    { value: 'eo - эсперанто', label: 'eo - эсперанто' },
    { value: 'et - эстонский', label: 'et - эстонский' },
    { value: 'jw - яванский', label: 'jw - яванский' },
    { value: 'ja - японский', label: 'ja - японский' },
]);
